### ISSUE TITLE
`delta%state` initialization missing in dUdt function implementations

### ISSUE THREAD

**Issue by milancurcic** [Fortran-FOSS-Programmers/FOODIE#19]
Hi Stefano,

I noticed that in the multi-level implementation of R(u,t) function implementations, you did not initialize the state after allocating the array, for example in case of Lorenz:

``` fortran
  pure function dLorenz_dt(self, n) result(dState_dt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Time derivative of Lorenz field.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(lorenz),          intent(IN) :: self      !< Lorenz field.
  integer(I_P), optional, intent(IN) :: n         !< Time level.
  class(integrand), allocatable      :: dState_dt !< Lorenz field time derivative.
  type(lorenz),     allocatable      :: delta     !< Delta state used as temporary variables.
  integer                            :: dn        !< Time level, dummy variable.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  ! preparing temporary delta
  allocate(delta)
  delta%dims = self%dims
  delta%steps = self%steps
  allocate(delta%state(1:self%dims, 1:self%steps))
  !delta%state = 0_R_P ! <<< delta%state should be initialized here
  delta%sigma = self%sigma
  delta%rho = self%rho
  delta%beta = self%beta
  ! Lorenz equations
  dn = self%steps ; if (present(n)) dn = n
  delta%state(1, dn) = self%sigma * (self%state(2, dn) - self%state(1, dn))
  delta%state(2, dn) = self%state(1, dn) * (self%rho - self%state(3, dn)) - self%state(2, dn)
  delta%state(3, dn) = self%state(1, dn) * self%state(2, dn) - self%beta * self%state(3, dn)
  call move_alloc(delta, dState_dt)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction dLorenz_dt
```

Same is true for the oscillation equations, and I find that initializing to zero now changes the solution from gibberish to just moderately wrong. For example, see the two examples for oscillation equation, first without initialization (notice the y-axis magnitude):

![oscillation_integration-ab-2](https://cloud.githubusercontent.com/assets/4133310/9701348/b2f24402-53f2-11e5-8213-5fa8a0260692.png)

then with initialization of `delta%state = 0_R_P`:

![oscillation_integration-ab-2](https://cloud.githubusercontent.com/assets/4133310/9701349/bd468170-53f2-11e5-8651-48faf13732f9.png)

 It is still difficult to test this correctly because of the issue https://github.com/Fortran-FOSS-Programmers/FOODiE/issues/18. 

If you agree with me that `delta%state` should be initialized to 0 after allocation, I can apply these changes in the current tests that we have.

**Comment by szaghi** [comment]
Absolutely yes! I have not yet started the correctness/accuracy analysis but this is a bug for sure, the state U must be initialized! Thank you Milan for going forward :-)

**Comment by milancurcic** [comment]
Resolved, see https://github.com/Fortran-FOSS-Programmers/FOODiE/commit/402791d8cee145513e5b994a90e0bbe20a565a04.
