### ISSUE TITLE
How to parallelize (OpenMP) procedural version of Euler 1D test

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/FOODIE#25]
Hi all,

answering to a question of @rouson I have noted that for the _procedural_ version of the OpenMP Euler 1D test I have missed to parallalize an important loop. See the following
##### Procedural integrate

This is the _hard-coded-Euler-1D_ RK integrator

``` fortran
  subroutine integrate_rk(self, U, stage, Dt, t)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Integrate field with explicit TVD (or SSP) Runge-Kutta scheme.
  !<
  !< @note This method can be used **after** the integrator is created (i.e. the RK coeficients are initialized).
  !---------------------------------------------------------------------------------------------------------------------------------
  class(tvd_runge_kutta_integrator), intent(IN)    :: self      !< Actual RK integrator.
  class(euler_1D_openmp),            intent(INOUT) :: U         !< Field to be integrated.
  class(euler_1D_openmp),            intent(INOUT) :: stage(1:) !< Runge-Kutta stages [1:stages].
  real(R_P),                         intent(IN)    :: Dt        !< Time step.
  real(R_P),                         intent(IN)    :: t         !< Time.
  integer(I_P)                                     :: s         !< First stages counter.
  integer(I_P)                                     :: ss        !< Second stages counter.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  ! computing stages
  do s=1, self%stages
    stage(s) = U ! parallelized
    do ss=1, s - 1
      stage(s)%U = stage(s)%U + stage(ss)%U * (Dt * self%alph(s, ss))
    enddo
    stage(s) = stage(s)%t()  ! parallelized
  enddo
  ! computing new time step
  do s=1, self%stages
    U%U = U%U + stage(s)%U * (Dt * self%beta(s))
  enddo
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine integrate_rk
```

The stages computing and Euler field new time step loops are not parallelized. Only the defined assignments and the `%t()` operator are parallel. Now consider the present FOODIE equivalent integrator.
##### FOODIE integrate

``` fortran
  subroutine integrate(self, U, stage, Dt, t)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Integrate field with explicit TVD (or SSP) Runge-Kutta scheme.
  !<
  !< @note This method can be used **after** the integrator is created (i.e. the RK coefficients are initialized).
  !---------------------------------------------------------------------------------------------------------------------------------
  class(tvd_runge_kutta_integrator), intent(IN)    :: self      !< Actual RK integrator.
  class(integrand),                  intent(INOUT) :: U         !< Field to be integrated.
  class(integrand),                  intent(INOUT) :: stage(1:) !< Runge-Kutta stages [1:stages].
  real(R_P),                         intent(IN)    :: Dt        !< Time step.
  real(R_P),                         intent(IN)    :: t         !< Time.
  integer(I_P)                                     :: s         !< First stages counter.
  integer(I_P)                                     :: ss        !< Second stages counter.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  select type(stage)
  class is(integrand)
    ! computing stages
    do s=1, self%stages
      stage(s) = U
      do ss=1, s - 1
        stage(s) = stage(s) + stage(ss) * (Dt * self%alph(s, ss))
      enddo
      stage(s) = stage(s)%t(t=t + self%gamm(s) * Dt)
    enddo
    ! computing new time step
    do s=1, self%stages
      U = U +  stage(s) * (Dt * self%beta(s))
    enddo
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine integrate
```

Again there is not explicit parallelism. However, in this FOODIE integrator all part are parallelized because the defined operators `+ * =` are parallel.
### Considerations

I think this is the reason why the FOODIE-aware version scales better (I am not considering the absolute cpu time, I am considering only the parallel scaling): in the FOODIE-aware version all _ingredients_ are easily _parallelizable_ (in this sense, having no side effect helps a lot) and they are, whereas in the procedural version it is not trivial (for me) how to parallelize all part (not only the assignments that are already parallelized). 

At a first superficial thought, I can modify the procedural version with this:

``` fortran
  !$OMP PARALLEL DO PRIVATE(s, ss) SHARED(U, stage, Dt, self)
  do s=1, self%stages
    stage(s) = U ! parallelized
    do ss=1, s - 1
      stage(s)%U = stage(s)%U + stage(ss)%U * (Dt * self%alph(s, ss))
    enddo
    stage(s) = stage(s)%t()  ! parallelized
  enddo
  ! computing new time step
  !$OMP PARALLEL DO PRIVATE(s) SHARED(U, stage, Dt, self)
  do s=1, self%stages
    U%U = U%U + stage(s)%U * (Dt * self%beta(s))
  enddo
```

I have not tried, but I guess that this modification does not provide much more parallelism (the stages are only 5...). I can try to tune with _collapse_ or other workarounds, but I feel this is not the best approach. 

The question (to specifically @francescosalvadore @muellermichel but also to all): how do you parallelize this procedural integrator? Do I have to restore all the defined operators and parallelized them? In this sense, the abstract FOODIE approach seems to be more _natural_. Do I have to try to parallelize the inner loops (`%U` is an array)?

**Comment by szaghi** [comment]
I can confirm that on my workstation FOODIE-aware and procedural code (as presently implemented) have also the same absolute CPU-time consumption, see this page from the manuscript draft
[page.pdf](https://github.com/Fortran-FOSS-Programmers/FOODIE/files/18514/page.pdf)

However, the problem on which is the best way to parallelize procedural code persists.

**Comment by zbeekman** [comment]
@szaghi please remind me to take a look at this next week.

**Comment by szaghi** [comment]
@zbeekman thank you very much! I will do it. Anyhow, now I know a possible solution (thank you @francescosalvadore ): use a _work sharing_ directive. Not tested yet...

**Comment by szaghi** [comment]
I will do some test to check if @francescosalvadore suggestion makes some differences. I will reopen (or open a new) this issue in case it is necessary.
