### ISSUE TITLE
HPC resources: proposal for a grant on European PRACE network

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/FOODIE#28]
@milancurcic @rouson @zbeekman and all

Dear All,
today I have devoted my break to write a proposal for obtaining HPC resources on the European [PRACE network](http://www.prace-ri.eu/). In few words, PRACE gathers some HPC facilities in the Europe supporting research projects. 

The proposal I have written is of _Preparatory Access type B_ type. Such a type is essentially devoted to assessing the performance of codes in order to _certify_ that those codes are allowed for a full PRACE access grant. In few words, the preparatory access grants allow developers to test their codes on HPC facilities. In particular, the _type B_ are grants that do not require support from PRACE people. Consequently, such a grant type is ideal for FOODIE: we just need to assess its performance into a real HPC scenario. Moreover, the limited resources of such a grant should give us more hope that the grant will be obtained. Here at INSEAN we have already obtained one of this grant for another project.

If the grant will be provided, we will obtain access to a _small/medium_ HPC facility. I have requested to use [FERMI](http://www.hpc.cineca.it/content/ibm-fermi-user-guide) and [Curie thin](http://www-hpc.cea.fr/en/complexe/tgcc-curie.htm) clusters. Such resources should be allow us to test FOODIE up to thousands of cores in heterogeneous scenario (Fermi is a IBM-BlueGene/Q machine while Curie thin is a Intel® Sandy Bridge EP one).

Attached here there is the draft of our proposal. I would like to have you as collaborators (even if I think this is not strictly required for success of the proposal): if you accept to be a collaborator you will not be asked to do anything, but you will have the possibility to directly access to the clusters for checking/correcting my errors/horrors :-)

In the case you agree to be a collaborator, please check the information I have added about your CV. I think that Milan's data should be correct, while the Damian's and Izaak's ones are very doubtful: in particular I am not sure about your affiliations (for Izaak I have added the University of Maryland, but Izaak has so many others that I am confused about Princeton/Sourcery Institute). The same is for Damian (Sourcery/Stanford). In particular for the proposal I need to know your birth date.

The last deadline for this year is 1st December. If accepted, the grant should start from 1st January 2016.

Let me know what you think about this proposal.

See you soon.

P.S. all other members of the group interested on this are welcome to join us!

[PRACE PR - Export on 2015-11-25 at 14.15.22.pdf](https://github.com/Fortran-FOSS-Programmers/FOODIE/files/43889/PRACE.PR.-.Export.on.2015-11-25.at.14.15.22.pdf)

**Comment by giacrossi** [comment]
Dear all,
I'm very interested in this project! I've observed all your incredible
progresses to develop a so powerful software like FOODiE, and now, if I
can, I want to give my very poor and little contribution :-)

Can you add me to the PRACE proposal?

Thank you!

See you soon

Giacomo

**Comment by szaghi** [comment]
@giacombum you are now a collaborator for the PRACE proposal. In the case the grant will be obtained your help will be surely appreciated.

See you soon.

**Comment by zbeekman** [comment]
Hi @szaghi, I don't have time to look at this now, since I am traveling for the Thanksgiving holiday. I'll look at this next week and get back to you. I'm certainly interested in collaborating on the PRACE proposal, but need more time to read/research/consider the details.

**Comment by szaghi** [comment]
@zbeekman Do not worry, we have still some days. I will be very happy to have you into the proposal: you are not required to anything, you will only obtain the direct access to the resources. Anyhow, I will upload the results here, thus also others that will not join the proposal will be able control the results and check/modify/propose/critic the HPC tests. FYI I am setting up a 2D test just to have a more reasonable production test.

See you soon and I wish you have a wonderful Thanksgiving holiday!

**Comment by rouson** [comment]
If you push the proposal to a repository, I hope to have the time to make a few edits by Monday.  I recommend BitBucket because private repositories are free there. If you email me privately, I'll reply with my date of birth, but thanks for estimating that I'm me a little younger than I actually am. :)

**Comment by szaghi** [comment]
@rouson 
Unfortunately, the proposal can be compiled only by means the online form: the attached PDF is automatically generated by the online form. Milan sent me his corrections by email: I think this is a good workflow for speedup the proposal submission.

The next cut-off date for the submission is:

1 December 2015 (23rd cut-off) > 11:00 AM CET

Therefore I think that with some emails-iteration we can write a good proposal.

I am sending a private emails to all who have manifested interest into the proposal.

See you soon.

**Comment by zbeekman** [comment]
@szaghi Stefano, I sent you my birth date, official position, and affiliation, and preferred email address for correspondence in an email. I just wanted to make sure you received it.

**Comment by szaghi** [comment]
Dear all, i have submitted the proposal with all of us. For milan, izaak
and Giacomo I have used the correct bio-data they sent me, for damian i
have used a wrong birth date because he does not send me the correct one. I
am sorry for this accellaration but tomorrow will be the last deadline for
this year and I am now busy due to my daugther health... See you next days
Il 30/nov/2015 16:16 "Izaak Beekman" notifications@github.com ha scritto:

**Comment by milancurcic** [comment]
Hi Stefano, thank you. I hope your daughter gets better soon. When you get the chance, can you please attach the submitted proposal for our reference?

Cheers,
milan

**Comment by szaghi** [comment]
Ho damian i think later tonight i could send you a private email with the
proposal. I should have the chance to modify it until tomorrow but i am
busy with hospital until afteenoon of tomorrow (i hope) so the eventual
corrections should come late tonight for me. Ser you later.
Il 30/nov/2015 17:48 "Milan Curcic" notifications@github.com ha scritto:

**Comment by szaghi** [comment]
Sorry, i see now it was milan... See you later
Il 30/nov/2015 17:48 "Milan Curcic" notifications@github.com ha scritto:

**Comment by Tobychev** [comment]
Sorry to bother you with these sorts of comments @szaghi, buy maybe this issue can be closed now?

**Comment by szaghi** [comment]
@Tobychev Do not worry, you do not bother, never. 

I like to leave this open because I have not yet recieved the response of our proposal. Today I will try to conctact my _insider trading_ at CINECA.

**Comment by szaghi** [comment]
Even the worst day could bring some good news:

> After evaluation, the Board of Directors decided that your proposal will be awarded:
> -        250.000 core-hours on Fermi, CINECA, Italy
> -        100.000 core-hours on MareNostrum, BSC, Spain

So we will have 250 Kcore-hours on a [BlueGene/Q](http://www.hpc.cineca.it/content/ibm-fermi-user-guide#systemarchitecture) system and 100 Kcore-hours on a  [Intel Sandy Bridge](https://www.bsc.es/marenostrum-support-services/mn3) cluster.

Soon I will give you (via email) details on how create an account on both system. 

I have to complete the 2D test for this grant: I hope tomorrow will be better than today.

See you soon.

**Comment by zbeekman** [comment]
:clap: :bow: @szaghi you rock!

**Comment by szaghi** [comment]
Dear All,

I am closing this issue and opening a more specific one on how (best) use our grant.

See you soon.
