### ISSUE TITLE
Higher order Adams formula

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/FOODIE#30]
If there is any interest, I have higher order Adams formulas coded up [here](https://github.com/jacobwilliams/FOODIE/commit/360c25a1d526a0a5f0d5ec7c7472a3db726957bd).

**Comment by szaghi** [comment]
Absolutely yes! @jacobwilliams thank you very much it very appreciated!

**Comment by szaghi** [comment]
@jacobwilliams 

The master branch of FOODIE has now your great work, thank you very much.

Please, consider to join us, we will be very happy!
