### ISSUE TITLE
Enabling FOODIE compilation on Fermi

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/FOODIE#33]
Currently, IBM XL Fortran complains with a lot of issues...

I am solving it right now.

**Comment by szaghi** [comment]
Fixed in v0.1.4

### Makefile(s) system

For improving the Fermi tests handling I need to modify Makefile(s) system: unfortunately on Fermi Python setup if very out-dated (2.6), thus FoBiS does not work properly (even if it can be installed) and I have to rely on GNU Make. I will modify @milancurcic makefiles to be more productive on Fermi, I am sorry if I will _ruin_ Milan work :cry:

**Comment by milancurcic** [comment]
@szaghi Great! I am happy that those Makefiles will end up being useful :)
