### ISSUE TITLE
Will spatial differencing algorithms be part of FOODiE?

### ISSUE THREAD

**Issue by milancurcic** [Fortran-FOSS-Programmers/FOODIE#5]
What the title says - will spatial differencing schemes be part of FOODiE? For example centered, upstream schemes of various orders, MPDATA family of schemes, etc.?

**Comment by zbeekman** [comment]
For PDE solvers or for ODE solvers like BVPs?

**Comment by milancurcic** [comment]
Both. :)

**Comment by zbeekman** [comment]
I was thinking it would be for integration of ODE IVPs mostly. Useful as a set of time integrators for PDE solvers, but not including the spatial differencing etc. I suppose algorithms for BVPs could be added too, but I feel like adding spatial differencing schemes is beyond the scope of a good library of ODE IVP integrators. The applications I am planning to use this for are CFD time integrators mostly. This could allow some dynamic choice of time integrator through a strategy pattern and be very modular/flexible if using ADT calculus pattern from Rouson et al.

**Comment by zbeekman** [comment]
But that’s not to say I necessarily oppose the idea. I just think it might be better suited to a parallel project, which is designed compatibly with ADT calculus.

**Comment by milancurcic** [comment]
:+1: Got it, thanks! Will keep thread open for further discussion.

**Comment by zbeekman** [comment]
also, I defer to @szaghi’s judgement

**Comment by szaghi** [comment]
This depends from us. My basic idea was to support only ODE time-like integration, but if you think that spatial operators could be implemented simply and they are useful, we can try.

**Comment by szaghi** [comment]
Yes, I am of the same idea of zaak.

Indeed, I have to do a `coming out`:

> build with all of you a set of small kiss libraries for numerical applications

I am most interested in PDEs but I would like be as agnostic as possible.

A spoiler... in my radar there the following small projects (like WenOOF and FOODiE):
- boundary values solver, i.e. spatial operators;
- multigrid schemes;
- octree structure data;
- Riemann solvers;
-  many other...

Not in this  rigorous order... all small kiss libraries with OOD and with your help :-)

**Comment by szaghi** [comment]
HI all, 

I have now more _consciousness thoughts_ about libraries like FOODiE could operate thus I come to intention to strictly follow the _method of lines_, leaving FOODiE to face with ONLY IVPs. Soon I will try  implement a FOODiE-like library for BVPs (I will start with some basic assumptions, e.g. how the space-domain is discretized, how the BC are imposed, etc...), but I like FOODiE to be not aware on how the PDE is semi-discretized to the ODE by a method of lines appraoch.

I am closing this issue, but feel free to reopen it for further discussions.
