### ISSUE TITLE
Problem with operators overloading

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/FOODIE#8]
Hi all,

implementing the Burgers' test, I faced with some problems with operators overloading. 

Let us consider [type_integrand](https://github.com/Fortran-FOSS-Programmers/FOODiE/blob/master/src/lib/type_integrand.f90#L18), its definition is

``` fortran
type, abstract :: integrand
  !< Abstract type for building FOODiE ODE integrators.
  contains
    ! public deferred procedures that concrete interpolators must implement
    procedure(time_derivative),      pass(self), deferred, public :: t                       !< Time derivative, residuals function.
    procedure(integrand_op_real),    pass(lhs),  deferred, public :: integrand_multiply_real !< Integrand * real operator.
    procedure(real_op_integrand),    pass(rhs),  deferred, public :: real_multiply_integrand !< Real * integrand operator.
    procedure(symmetric_operator),   pass(lhs),  deferred, public :: add                     !< Integrand + integrand oprator.
    procedure(assignment_integrand), pass(lhs),  deferred, public :: assign_integrand        !< Integrand = integrand.
    procedure(assignment_real),      pass(lhs),  deferred, public :: assign_real             !< Integrand = real.
    ! operators overloading
    generic, public :: operator(+) => add                                              !< Overloading + operator.
    generic, public :: operator(*) => real_multiply_integrand, integrand_multiply_real !< Overloading * operator.
    generic, public :: assignment(=) => assign_integrand, assign_real                  !< Overloading = assignament.
endtype integrand
```

Now consider the Lorenz [concrete extension](https://github.com/Fortran-FOSS-Programmers/FOODiE/blob/master/src/tests/lorenz/type_lorenz.f90#L19) of the above abstract type

``` fortran
type, extends(integrand) :: lorenz
  !< Lorenz equations field.
  !<
  !< It is a FOODiE integrand class.
  private
  real(R_P), dimension(:), allocatable :: state        !< Solution vector.
  real(R_P)                            :: sigma=0._R_P !< Lorenz \(\sigma\).
  real(R_P)                            :: rho=0._R_P   !< Lorenz \(\rho\).
  real(R_P)                            :: beta=0._R_P  !< Lorenz \(\beta\).
  contains
    procedure, pass(self), public :: output                                          !< Extract Lorenz field.
    procedure, pass(self), public :: t => dLorenz_dt                                 !< Time derivate, resiuduals function.
    procedure, pass(lhs),  public :: integrand_multiply_real => lorenz_multiply_real !< lorenz * real operator.
    procedure, pass(rhs),  public :: real_multiply_integrand => real_multiply_lorenz !< Real * Lorenz operator.
    procedure, pass(lhs),  public :: add => add_lorenz                               !< Lorenz + Lorenz oprator.
    procedure, pass(lhs),  public :: assign_integrand => lorenz_assign_lorenz        !< Lorenz = Lorenz.
    procedure, pass(lhs),  public :: assign_real => lorenz_assign_real               !< Lorenz = real.
endtype lorenz
```

The overloaded operator `*` should have both `lorenz * real_scalar` and `real_scalar * lorenz`, but only the first work. For example [Euler integrator](https://github.com/Fortran-FOSS-Programmers/FOODiE/blob/master/src/lib/foodie_integrator_euler_explicit.f90#L39) does not compile if I change it
#### working

``` fortran
  subroutine integrate(field, dt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Integrate field with explicit Euler scheme, 1st order.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(integrand), intent(INOUT) :: field !< Field to be integrated.
  real(R_P),        intent(in)    :: dt    !< Time step.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  field = field + field%t()*dt
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine integrate
```
#### not working

changing the position of `dt`

``` fortran
  subroutine integrate(field, dt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Integrate field with explicit Euler scheme, 1st order.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(integrand), intent(INOUT) :: field !< Field to be integrated.
  real(R_P),        intent(in)    :: dt    !< Time step.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  field = field + dt*field%t()
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine integrate
```

This becomes even more problematic if the _high level equation_ implementation contains a more complex operators combination. For example for the [Burgers residual function](https://github.com/Fortran-FOSS-Programmers/FOODiE/blob/master/src/tests/burgers/type_burgers.f90#L104) (involving the space operator) I have had to split the computation into more than on statement (see the delta computation):

``` fortran
  pure function dBurgers_dt(self) result(dState_dt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Time derivative of Burgers field, residuals function.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(burgers), intent(IN)    :: self      !< Burgers field.
  class(integrand), allocatable :: dState_dt !< Burgers field time derivative.
  type(burgers),    allocatable :: delta     !< Delta state used as temporary variables.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  ! preparing temporary variables
  allocate(delta, source=self)
  ! Burgers residuals
  delta = self%xx() * self%nu
  delta = delta - self * self%x()
  call move_alloc (delta, dState_dt)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction dBurgers_dt
```

Do you have any idea?

P.S. Intel Fortran seems to be more _sensible_ to this problem...

**Comment by rouson** [comment]
This reminds me that I need to give you access to the latest version of the solver, which has a corrected stability criterion for setting the time step and which has much more stringent testing to detect failure.  Previous versions could set too large a time step, become unstable, produce NaN results, but fail silently. I'll send you an invitation to access the repository shortly.

**Comment by szaghi** [comment]
@rouson Thank you very much!

Indeed, I do not implement your 6th order periodic solver, just a very naive central one. I think that the problem is not related to the CFL. The Euler integrator must provide the identical result of the RK(1,1) but they differ with the same CFL (imposed!), see these

![burgers_integration-euler](https://cloud.githubusercontent.com/assets/1661942/9228897/e4a0fc04-411a-11e5-81fb-9b69790b7ca4.png)
![burgers_integration-rk-1](https://cloud.githubusercontent.com/assets/1661942/9228898/e4a4a336-411a-11e5-815b-e64c77182bcf.png)

it seems that the RK class does not integrate the same equation (issue on the viscosity?) of the Euler one... I think it is related to the buggy implementation of overloaded operators that I made...

**Comment by rouson** [comment]
The central difference solver is the one I updated.  It is now available at https://github.com/sourceryinstitute/Scientific-Software-Design.

**Comment by milancurcic** [comment]
Reproduced the issue with Intel Fortran v15.0.0:

```
ifort -c -cpp -O0 -w -C foodie_integrator_euler_explicit.f90
foodie_integrator_euler_explicit.f90(49): error #6633: The type of the actual argument differs from the type of the dummy argument.
  field = field + dt*field%t()
---------------------^
compilation aborted for foodie_integrator_euler_explicit.f90 (code 1)
```

**Comment by rouson** [comment]
Yes, I’ve seen this before.  I might have even reported it, but I don’t think there is a current bug report associated with it so possibly it's a regression.   I’ve gotten a bit frustrated with the Intel compiler and haven’t reported bugs lately except when a consulting client pays me to do so.  Nonetheless, I recently started a repository to hold bug reports related the projects of myself, my collaborators, and my clients.  It would be great if you would submit this bug report to Intel and add it to my repository: http://github.com/sourceryinstitute/AdHoc.git.  Currently the repository only has one or two bug reports, but it includes a feature that is useful in this context: the codes get built and run at test-time rather than at build time.  This is important because most of the codes in this repository fail to compile, which is of course the whole point of the repository.  If the build system bails when it sees a compile-time error, then one has to delay the build to test time so that build failures can be reported as test failures and the remainder of the tests will continue to run despite many previous compiler errors. 

Also, the repository automatically writes the compiler error message into a file in the source tree and names the file according to the compiler identity and version.  This way the error messages can be archived and tracked via version control.  I really want to start blogging soon and hope to describe all this in a blog post or even possibly a conference paper if I can manage to find the time to write it up.

Do you have a strong motivation for using Intel rather than GNU?  When I perform a weighted average across all variables that matter most to me -- ranging from cost to portability to support for the standards to bugginess to performance (especially parallel performance with couriers), gfortran comes out way ahead of the pack for me.  Cray is a reasonably close second but loses to gfortran on the portability issue.

Damian

**Comment by szaghi** [comment]
@milancurcic thank you for testing, presently I have only intel v15.02 and the error is the same.

@rouson incredible... I was almost sure that it was not a bug. Year(s) ago I have a module with a lot of operators overloaded and it works correctly (but slow) with intel 12.x or 14.x.

> It would be great if you would submit this bug report to Intel 

Sure, now that the suspect of bug compiler is more concrete I am going to submit. There is a better way to do it?

> add it to my repository: http://github.com/sourceryinstitute/AdHoc.git. Currently the repository only has one or two bug reports, but it includes a feature that is useful in this context: the codes get built and run at test-time rather than at build time. This is important because most of the codes in this repository fail to compile, which is of course the whole point of the repository. If...

What? _Incredible_... very nice idea, your clients are very lucky! I will happy to contribute, later today I will study your repo, thank you very much!

> Do you have a strong motivation for using Intel rather than GNU? When I perform a weighted average across all variables that matter most to me -- ranging from cost to portability to support for the standards to bugginess to performance (especially parallel performance with couriers), gfortran comes out way ahead of the pack for me. Cray is a reasonably close second but loses to gfortran on the portability issue.

It is a long story. Before I try the OOP way my favorite was GNU gfortran, but when I started to play with OOP I found intel more advanced (in particular for allocatable deferred length string and allocatable array as member of derived type). Moreover, there was the _performance_ considerations: I runned very long time simulations (months/year) on relatively small clusters (up to 512/1024 cores, not using all cores, the clusters aren't mine...) in the past and most of these clusters were intel based: Intel compiler produced more optimized code thsn GNU (enabling all reasonable opyimizations for both compilers). My list of preferences was
1. IBM XL fortran (when I have access to it and to Blue-gene-q like cluster by means of public grants);
2. Intel Fortran;
3. GNU gfortran;
4. g95 (never used in production);
5. Others not yet tested;
6. PGI... if you point a cannon to my head...

However, the situation is very _fluid_ and GNU is now my favorite, but as a general rule I want to test my codes with all the compilers I have access to: before production, I always compile with _paranoiac debug/check/warn_ mode to ensure my codes being standard and portable. This does not ensure my codes are good, but calm my OCD soul :-)

**Comment by milancurcic** [comment]
Thanks, Damian.

> Do you have a strong motivation for using Intel rather than GNU?

No, other than being most familiar with Intel compiler suite. It will be useful to be able to try as many compilers as possible when diagnosing issues like this. GNU compiler is very outdated on our compute cluster at work,.as we don't use it for production runs. I just tried gfortran 4.8.2 on my laptop, and this version does not seem to support the `final` statement:

```
gfortran -c -cpp  foodie_integrator_tvd_runge_kutta.f90
foodie_integrator_tvd_runge_kutta.f90:99.34:

type :: tvd_runge_kutta_integrator
                                  1
Error: Finalization at (1) is not yet implemented
```

Perhaps time for an update :).

I will be able to test the multiplication overloading issue with Cray compilers this week and will let you know what I find.

**Comment by szaghi** [comment]
@milancurcic Thank you very much! I have not access to Cray compilers (and I know it is a good one).

I have just check with my GNU gfortran:

``` shell
→ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc-5.2.0/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 5.2.0 (GCC)
```

It works well with both the `dt` positions: compile and run as expected. Thus I am going to think this is a problem of the Intel Compiler. I am studying how submit this bug.

**Comment by rouson** [comment]
Yes, updating to a newer version of gfortran should provide support for FINAL.  What's the reason for needing FINAL?  The only times I've found use for it are when I'm wrapping C/C++.

**Comment by szaghi** [comment]
> What's the reason for needing FINAL? The only times I've found use for it are when I'm wrapping C/C++.

As a good practice, I use `final` always a derived type contains an allocatable or pointer member. Indeed, I think it is necessary for only pointer, but in doubt... If I understand right, `final` should be a user-defined _finalizer_ of a derived type, this make me more control (calming my nervous) on what happens when a _monster_ derived type vanishes... especially when I pollute the the type with pointers. For FOODiE specific case, I think it is not necessary because there is not any pointers, only allocatable.

**Comment by rouson** [comment]
I see. It would be interesting to how explicit deallocation impacts performance and memory usage. Regarding memory management, my book co-author Jim Xia, who was on the Fortran standards committee and on IBM's compiler test team, used to say, "Let the compiler do it's job."  I generally avoid doing things explicitly that the compiler can do for me because I generally assume the compiler knows best.

**Comment by rouson** [comment]
I see.  It would be interesting to find out how explicit deallocation in a FINAL subroutine impacts performance and memory utilization. It certainly can be helpful (even critical) in cases where the compiler has causes memory leaks and most compilers did for allocatable components sometime back, but I think most of those issues have been resolved.  

Regarding memory management, my book co-author Jim Xia, who was on the IBM compiler test team and on the Fortran standards committee, used to say, "Let the compiler do it's job."  I generally avoid doing things explicitly that the compiler can do for me. I assume the compiler knows when, where, and how to do it better than I do.

**Comment by szaghi** [comment]
> I see. It would be interesting to find out how explicit deallocation in a FINAL subroutine impacts performance and memory utilization. It certainly can be helpful (even critical) in cases where the compiler has causes memory leaks and most compilers did for allocatable components sometime back, but I think most of those issues have been resolved.

Using the Intel inspector tool I had found some possible memory leaks, thus I started to force my self to insert explicit `final` procedure. Indeed, I do not remember if the addiction of an explicit `final` solves the memory leaks that indeed seemed to be a false positive warning rather than a real problem.

> Regarding memory management, my book co-author Jim Xia, who was on the IBM compiler test team and on the Fortran standards committee, used to say, "Let the compiler do it's job." I generally avoid doing things explicitly that the compiler can do for me. I assume the compiler knows when, where, and how to do it better than I do.

Without doubt this is true, you (compiler developers, standard designers and experienced programmers) do it better, but I prefer to be as `explicit` as possible and there are exceptions to the above rule... For example OpenMP... it is very nice (in theory) it just does a lot of nice stuff for us, but in practice it has many limits and we have to hard-hack it and many times an MPI equivalent obtains higher performance even on a shared-memory multi-cores architecture, thus IMO compilers do it better in _may cases_, but not always :-)

**Comment by szaghi** [comment]
@rouson 

I have submitted the possible presence of the bug on the Intel Forum [here](https://software.intel.com/en-us/forums/topic/583935). Thus I have set-up a minimal working code raising the problem. How can I add it to your bug-database-incredible-repository? Testing the minimal working example, I realize that what make ifort crazy is not the operators overloading itself (this explains why my previous codes work), rather the _passage_ trough the abstract type and the abstract calculus library! If I eliminate the passage from the abstract calculus library and implement it directly into a concrete type, ifort compiles the code and produces the expected results. For your interest I report below the minimal working example raising the _bug_. Note that gfortran 5.2 compiles it correctly and produces the expected results! Great GNU!

``` fortran
module type_abstract_buggy
implicit none
private
public :: abstract_buggy

type, abstract :: abstract_buggy
  contains
    ! public methods
    procedure(abstract_printf), public, deferred :: printf
    generic,                    public           :: operator(*) => buggy_multiply_scalar, scalar_multiply_buggy
    generic,                    public           :: assignment(=) => buggy_assign_buggy
    ! private methods
    procedure(abstract_buggy_multiply_scalar),       pass(lhs), private, deferred :: buggy_multiply_scalar
    procedure(scalar_multiply_abstract_buggy),       pass(rhs), private, deferred :: scalar_multiply_buggy
    procedure(abstract_buggy_assign_abstract_buggy), pass(lhs), private, deferred :: buggy_assign_buggy
endtype abstract_buggy
abstract interface
  subroutine abstract_printf(self)
  import :: abstract_buggy
  class(abstract_buggy), intent(IN) :: self
  endsubroutine abstract_printf

  function abstract_buggy_multiply_scalar(lhs, rhs) result(multy)
  import :: abstract_buggy
  class(abstract_buggy), intent(IN)  :: lhs
  integer,               intent(IN)  :: rhs
  class(abstract_buggy), allocatable :: multy
  endfunction abstract_buggy_multiply_scalar

  function scalar_multiply_abstract_buggy(lhs, rhs) result(multy)
  import :: abstract_buggy
  integer,               intent(IN)  :: lhs
  class(abstract_buggy), intent(IN)  :: rhs
  class(abstract_buggy), allocatable :: multy
  endfunction scalar_multiply_abstract_buggy

  pure subroutine abstract_buggy_assign_abstract_buggy(lhs, rhs)
  import :: abstract_buggy
  class(abstract_buggy), intent(INOUT) :: lhs
  class(abstract_buggy), intent(IN)    :: rhs
  endsubroutine abstract_buggy_assign_abstract_buggy
endinterface
endmodule type_abstract_buggy

module lib_abstract_buggy
use type_abstract_buggy, only : abstract_buggy
implicit none
private
public :: raise_bug
contains
  subroutine raise_bug(bug, scalar)
  class(abstract_buggy), intent(INOUT) :: bug
  integer,               intent(IN)    :: scalar

  call bug%printf()
  bug = bug * scalar
  call bug%printf()
  bug = scalar * bug
  call bug%printf()
  endsubroutine raise_bug
endmodule lib_abstract_buggy

module type_buggy
use type_abstract_buggy, only : abstract_buggy
implicit none
private
public :: buggy

type, extends(abstract_buggy) :: buggy
  private
  real, dimension(:), allocatable :: array
  integer                         :: scalar=0
  contains
    ! public methods
    procedure, pass(self), public :: printf
    ! private methods
    procedure, pass(lhs), private :: buggy_multiply_scalar
    procedure, pass(rhs), private :: scalar_multiply_buggy
    procedure, pass(lhs), private :: buggy_assign_buggy
endtype buggy
interface buggy
  procedure create_buggy
endinterface
contains
  pure function create_buggy(array, scalar) result(bug)
  real, dimension(:), intent(IN) :: array
  integer,            intent(IN) :: scalar
  type(buggy)                    :: bug

  bug%array = array
  bug%scalar = scalar
  return
  endfunction create_buggy

  subroutine printf(self)
  class(buggy), intent(IN) :: self
  integer      :: i

  print "(A)", "Array:"
  do i=1, size(self%array)
    print*, self%array(i)
  enddo
  print "(A,I5)", "Scalar: ", self%scalar
  endsubroutine printf

  function buggy_multiply_scalar(lhs, rhs) result(multy)
  class(buggy), intent(IN)           :: lhs
  integer,      intent(IN)           :: rhs
  class(abstract_buggy), allocatable :: multy
  type(buggy),           allocatable :: multy_tmp

  allocate(buggy :: multy_tmp)
  multy_tmp%array = lhs%array * rhs
  multy_tmp%scalar = lhs%scalar
  call move_alloc(multy_tmp, multy)
  return
  endfunction buggy_multiply_scalar

  pure function scalar_multiply_buggy(lhs, rhs) result(multy)
  integer,      intent(IN)           :: lhs
  class(buggy), intent(IN)           :: rhs
  class(abstract_buggy), allocatable :: multy
  type(buggy),           allocatable :: multy_tmp

  allocate(buggy :: multy_tmp)
  multy_tmp%array = rhs%array * lhs
  multy_tmp%scalar = rhs%scalar
  call move_alloc(multy_tmp, multy)
  return
  endfunction scalar_multiply_buggy

  pure subroutine buggy_assign_buggy(lhs, rhs)
  class(buggy),          intent(INOUT) :: lhs
  class(abstract_buggy), intent(IN)    :: rhs

  select type(rhs)
  class is(buggy)
    if (allocated(rhs%array)) lhs%array = rhs%array
    lhs%scalar = rhs%scalar
  endselect
  return
  endsubroutine buggy_assign_buggy
endmodule type_buggy

program ifort_bug
use lib_abstract_buggy, only : raise_bug
use type_buggy, only : buggy
implicit none
type(buggy) :: bug

bug = buggy(array=[1., 2., 3.], scalar=3)
call raise_bug(bug=bug, scalar=2)
stop
endprogram ifort_bug 
```

to be compiled with:
- ifort: `ifort -O0 -debug all -check all -warn all -traceback -assume realloc_lhs -std08 ifort-bug.f90`
- gfortran: `gfortran -O0 -fcheck=all -fbacktrace -std=f2008 -fall-intrinsics -frealloc-lhs ifort-bug.f90`

**Comment by szaghi** [comment]
@rouson Steve Lionel, aka Dr. Fortran, has opened the issue DPD200374902 for this possible bug. I will let you know how it evolves.

**Comment by rouson** [comment]
I started writing a longer response that somehow got deleted so here's the short version:

Getting a response from a compiler team often requires going to much greater lengths to isolate the bug (which will very likely be their first step if you don't save them the work by doing it for them).  Stare at the code really hard and ask yourself, "Does this feature on this line have to be here to demonstrate the bug?"

Without going through an exhaustive list, I'd suggest that you could probably
1. Delete argument intent.
2. Delete "public" and "private"
3. Delete "pure" 
4. Invoke some procedures directly rather than through operators or just delete all procedures unrelated to the error.
5. Eliminate modules by instead incorporating the code into the main program.
6. Simplify derived types, e.g., do I really need components
7. My final step before submitting a bug is to even delete "implicit none" if it's not essential to reproducing the bug.

These are just some thoughts base on an initial review.   I almost always end up with a code that is 20-30 lines long in the end.  I bet your code wouldn't have to be much longer than that to demonstrate the bug.   Compiler teams love bug reports that are short because such reports shine a narrowly focused, bright spotlight on the problem.

**Comment by szaghi** [comment]
@rouson wow, you are absolutely right! I had very few time for preparing the bug report, thus I do not accurately consider the work of the compiler developers, I am very sorry. As soon as possible I will try to restructure the buggy test in order to obtain a really minimal bug-raising program. Thank very much for your help, your posts are very interesting!

Moreover, another experienced Fortraner like you (FortranFan is his nickname on google group), seems to have found a possible reason for the Intel failure: it seems that the constructor function overloading the name of the derived (in the my not-so-minimal example) "confuse" the compiler. If we use an `init` subroutine as constructor that does not overload the derived type name, intel (not clear which versions, 15 or 16) works correctly.

Thank you all!
